### ISSUE TITLE
dec16 and inc16 are missing

### ISSUE THREAD

**Issue by pararaum** [demesos/LAMAlib#1]
The 16bit macros are missing a macro to decrement and increment a 16-bit value by one. This macro could use the inc/dec assembler commands instead of adc/sbc. This macro is useful for incrementing or decrementing counters or pointers.

**Comment by demesos** [comment]
There are already macros for that, called **inc16** and **dec16**. If you want to do it on ax, there is **incax** and **decax**.

**Comment by pararaum** [comment]
Thanks, this macro has eluded me.
